services:
  webdis:
    image: nicolas/webdis:latest

  envoy:
    image: envoyproxy/envoy:v1.31.0
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
      - "10005:10005"
      - "9901:9901"
    volumes:
      - ./src/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./src/tls/envoy-tls-config:/etc/envoy/tls

  service:
    image: hashicorp/http-echo:0.2.3
    command: ["-text=Hello, world!"]

  ext_authz-opa-service:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    volumes:
      - ./src/opa-policies:/app/policies
      - ./src/tls/opa-tls-config:/app/tls

  static-opa:
    build:
      context: .
      dockerfile: ./src/Dockerfile.static-opa
    volumes:
      - ./src/static-opa-policies:/app/policies
      - ./src/tls/opa-tls-config:/app/tls


