
services:
  webdis:
    image: nicolas/webdis:latest
    container_name: webdis
    ports:
      - "6379:6379"
    networks:
      - cache

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webdis
    ports:
      - "443:443"
    networks:
      - cache
      - opa

networks:
  cache:
  opa:   

