services:
  opa:
    image: openpolicyagent/opa:latest
    command: run --server --config-file /config/config.yaml
    volumes:
      - ./policies:/policies
      - ./config:/config
    ports:
      - "8181:8181"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  log-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"

  opa-config:
    image: alpine
    volumes:
      - ./config:/config
    entrypoint: ["sh", "-c", "while true; do sleep 1000; done"]
